# 头部菜单，title: link
menu:
  Home: /
# Categorie: /categories
# Tags: /tags
# Archivio: /archives
# About: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
  - http://link.hhtjim.com/163/425570952.mp3
  - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)

music: false

welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover:
  - /img/welcome-cover.jpg

# 是否使用mathjax
mathjax: false

# 是否关闭默认滚动条
scrollbar: true

# Abilita riceca
local_search:
  # 是否启用
  enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# Link ai vari social
links:
  facebook: https://www.facebook.com/GildaFTF/
# twitter: https://www.facebook.com/GildaFTF/
# github: https://www.facebook.com/GildaFTF/
#  wechat: /img/logo.png
#  email: mailto:xxxx@gmail.com

# 备案
beian:
  # 是否显示备案信息
  enable: false
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: false
  # 备案号
  beianInfo: 冀ICP备xxxxxxx号
  # 链接地址
  link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: true
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: "d998927855844929a176"
  # 应用秘钥
  clientSecret: "daee6c703ffadf57a21beaa496fefd1aeebd3c58"
  # issue仓库名
  repo: "ftfansub.github.io"
  # Github名
  owner: "FTFansub"
  # Github名
  admin: ["zeriyu", "AttilioGiordano"]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

disqus:
  enable: false
  shortname: fairytailfansub

# 网站关键字
# keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-42556680-3

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
